services:
  - type: web
    name: medical-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: FIREBASE_CREDENTIALS
        sync: false
